# .rubocop.yml
# Disable the inherited requires
require: []

# Specify plugins explicitly
plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

# Inherit rules from the omakase configuration
inherit_from:
  - .rubocop_omakase.yml